CFLAGS =		/c /EHsc /D_CRT_SECURE_NO_DEPRECATE /O2 /DWIN32

TARGETS=		Triangle.exe

.SUFFIXES:		.c.obj

OBJDIR = .\Win32

.c{$(OBJDIR)}.obj:	
			cl /c $(CFLAGS) /Fo$@ $<

default all:		$(TARGETS)

    
COBJECTS =	$(OBJDIR)\Triangle.obj		

$(OBJDIR) :
    if not exist "$(OBJDIR)" mkdir "$(OBJDIR)"    
   
$(TARGETS):	$(OBJDIR) $(COBJECTS)
		cl $(COBJECTS)

clean:
	if exist "$(OBJDIR)" del /Q $(OBJDIR)\*.*
	del $(TARGETS)