      SUBROUTINEPC0V(N,V)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN
      DOUBLEPRECISIONV(*)
      INTEGERI
      DO1I=1,N
      V(I)=0.0D0
1     CONTINUE
      RETURN
      END
