      SUBROUTINEPCAXPY(N,IJA,S,V,A)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*)
      DOUBLEPRECISIONS,A(*),V(*)
      INTEGERK
CVDIR IGNORE RECRDEPS
CDIR$ IVDEP
      DO1K=1,N
      A(IJA(K))=A(IJA(K))+S*V(K)
1     CONTINUE
      RETURN
      END
