      SUBROUTINEPCBTRC(N,IBLKN,IBLK,IBLKS,IBTRM,IRTBM)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IBLKN,IBLK,IBLKS(IBLKN),IBTRM(*),IRTBM(*)
      INTEGERI,J,K
      IBTRM(1)=1
      DO1I=1,IBLKN
      IBTRM(I+1)=IBTRM(I)+IBLKS(I)
1     CONTINUE
      IF(IBLK.GT.0)THEN
      DO3I=1,N
      IRTBM(I)=(I-1)/IBLK+1
3     CONTINUE
      ELSE
      K=0
      DO5I=1,IBLKN
      DO7J=1,IBLKS(I)
      K=K+1
      IRTBM(K)=I
7     CONTINUE
5     CONTINUE
      ENDIF
      RETURN
      END
