      SUBROUTINEPCCRED(N,IJA,NBLACK,P,IP,ISP)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NBLACK,IJA(*),P(*),IP(*),ISP(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      INTEGERI,IJ,J,K,IPJ,NRED
      CALLPCSRIZ(N,IJA,ISP)
      CALLPCSRIX(N,IJA,ISP)
      NRED=RED2-RED1+1
      NBLACK=N-NRED
      DO10K=1,RED1-1
      IP(K)=-K
 10   CONTINUE
      DO20K=RED1,RED2
      IP(K)=K-RED1+1
 20   CONTINUE
      DO30K=RED2+1,N
      IP(K)=-(K-NRED)
 30   CONTINUE
      DO60I=RED1,RED2
      DO40IJ=IJA(I),IJA(I+1)-1
      J=IJA(IJ)
      IPJ=IP(J)
      IF(IPJ.GT.0)THEN
      IERR2=I
      IERR=19
      RETURN
      ENDIF
 40   CONTINUE
      DO50IJ=ISP(I),ISP(I+1)-1
      J=ISP(IJ)
      IPJ=IP(J)
      IF(IPJ.GT.0)THEN
      IERR2=I
      IERR=19
      RETURN
      ENDIF
 50   CONTINUE
 60   CONTINUE
      DO70I=1,N
      IF(IP(I).LT.0)THEN
      IP(I)=-IP(I)
      ELSE
      IP(I)=IP(I)+NBLACK
      ENDIF
      P(IP(I))=I
 70   CONTINUE
      RETURN
      END
