      SUBROUTINEPCD2I(IBLKN,IBLKS,IBTRM,IBTRMC,NBLCKB,C,IPVT,
     *D2I,V)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIBLKN,IBLKS(*),IBTRM(*),IBTRMC(*),NBLCKB,C(*),
     *IPVT(*)
      DOUBLEPRECISIONV(*),D2I(*)
      INTEGERK,I,II,J
      K=1
      J=1
      DO1I=NBLCKB+1,IBLKN
      II=C(I)
      CALLPCD2II(IBLKS(II),IBLKS(II),IPVT(J),D2I(K),V(IBTRM(II)))
      K=K+IBLKS(II)*IBLKS(II)
      J=J+IBLKS(II)
1     CONTINUE
      RETURN
      END
