      SUBROUTINEPCDMVA(N,NV,M,V,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NV
      DOUBLEPRECISIONM(N,*),V(*),W(*)
      INTEGERI,ONE
      ONE=1
      DO1I=1,NV
      CALLDAXPY(N,V(I),M(1,I),ONE,W,ONE)
1     CONTINUE
      RETURN
      END
