      SUBROUTINEPCICMS(ICODE,N,IJU,UD,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERICODE,N,IJU(*)
      DOUBLEPRECISIONW(*),UD(*)
      GOTO(1,2,3,4,5,6,7),ICODE+4
1     CONTINUE
      CALLPCMLIC(N,IJU,UD,W)
      CALLPCVMUL(N,W,W,UD)
      CALLPCMUIR(N,IJU,UD,W)
      RETURN
2     CONTINUE
      CALLPCMUIR(N,IJU,UD,W)
      RETURN
3     CONTINUE
      CALLPCMLIC(N,IJU,UD,W)
      CALLPCVMUL(N,W,W,UD)
      RETURN
4     CONTINUE
      RETURN
5     CONTINUE
      CALLPCVDIV(N,W,W,UD)
      CALLPCMLC(N,IJU,UD,W)
      RETURN
6     CONTINUE
      CALLPCMUR(N,IJU,UD,W)
      RETURN
7     CONTINUE
      CALLPCMUR(N,IJU,UD,W)
      CALLPCVDIV(N,W,W,UD)
      CALLPCMLC(N,IJU,UD,W)
      RETURN
      END
