      SUBROUTINEPCICMR(ICODE,N,IJL,IJU,L,D,U,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERICODE,N,IJL(*),IJU(*)
      DOUBLEPRECISIONW(*),L(*),D(*),U(*)
      GOTO(1,2,3,4,5,6,7),ICODE+4
1     CONTINUE
      CALLPCMLIR(N,IJL,L,W)
      CALLPCVMUL(N,W,W,D)
      CALLPCMUIR(N,IJU,U,W)
      RETURN
2     CONTINUE
      CALLPCMUIR(N,IJU,U,W)
      RETURN
3     CONTINUE
      CALLPCMLIR(N,IJL,L,W)
      CALLPCVMUL(N,W,W,D)
      RETURN
4     CONTINUE
      RETURN
5     CONTINUE
      CALLPCVDIV(N,W,W,D)
      CALLPCMLR(N,IJL,L,W)
      RETURN
6     CONTINUE
      CALLPCMUR(N,IJU,U,W)
      RETURN
7     CONTINUE
      CALLPCMUR(N,IJU,U,W)
      CALLPCVDIV(N,W,W,D)
      CALLPCMLR(N,IJL,L,W)
      RETURN
      END
