      SUBROUTINEPCILUF(MODIFY,N,IJA,IJL,IJU,A,LD,U,IROW,ROW)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      LOGICALMODIFY
      INTEGERN,IJA(*),IJL(*),IJU(*),IROW(*)
      DOUBLEPRECISIONA(*),LD(*),U(*),ROW(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      DOUBLEPRECISIONACCEL,RESID,ACC2
      COMMON/PCCOM2/ACCEL,RESID,ACC2
      SAVE/PCCOM2/
      INTEGERI,J,K,ONE
      ONE=1
      CALLDCOPY(N,A,ONE,LD,ONE)
      IF(ACCEL.NE.0.0D0)THEN
      DO1I=1,N
      LD(I)=LD(I)+ACCEL
1     CONTINUE
      ENDIF
      CALLPC0V(N,ROW)
      IF(MODIFY)THEN
      CALLPC0VI(N,IROW)
      DO3K=1,N
CVDIR PREFER SCALAR
      DO5J=IJL(K),IJL(K+1)-1
      ROW(IJL(J))=0.0D0
      IROW(IJL(J))=K
5     CONTINUE
CVDIR PREFER SCALAR
      DO7J=IJU(K),IJU(K+1)-1
      ROW(IJU(J))=0.0D0
      IROW(IJU(J))=K
7     CONTINUE
      IROW(K)=K
      ROW(K)=LD(K)
CVDIR PREFER SCALAR
      DO9J=IJA(K),IJA(K+1)-1
      ROW(IJA(J))=A(J)
9     CONTINUE
      DO11I=IJL(K),IJL(K+1)-1
      LD(I)=ROW(IJL(I))*LD(IJL(I))
CVDIR IGNORE RECRDEPS
CVDIR PREFER SCALAR
CDIR$ NOVECTOR
      DO13J=IJU(IJL(I)),IJU(IJL(I)+1)-1
      IF(IROW(IJU(J)).EQ.K)THEN
      ROW(IJU(J))=ROW(IJU(J))-ROW(IJL(I))*U(J)
      ELSE
      ROW(K)=ROW(K)-ACC2*ROW(IJL(I))*U(J)
      ENDIF
13    CONTINUE
CDIR$ VECTOR
11    CONTINUE
      IF(ROW(K).EQ.0)THEN
      IERR=5
      IERR2=K
      RETURN
      ENDIF
      LD(K)=1.0D0/ROW(K)
CVDIR PREFER SCALAR
      DO15J=IJU(K),IJU(K+1)-1
      U(J)=ROW(IJU(J))*LD(K)
15    CONTINUE
3     CONTINUE
      ELSE
      DO17K=1,N
CVDIR PREFER SCALAR
      DO19J=IJL(K),IJL(K+1)-1
      ROW(IJL(J))=0.0D0
19    CONTINUE
CVDIR PREFER SCALAR
      DO21J=IJU(K),IJU(K+1)-1
      ROW(IJU(J))=0.0D0
21    CONTINUE
      ROW(K)=LD(K)
CVDIR PREFER SCALAR
      DO23J=IJA(K),IJA(K+1)-1
      ROW(IJA(J))=A(J)
23    CONTINUE
      DO25I=IJL(K),IJL(K+1)-1
      LD(I)=ROW(IJL(I))*LD(IJL(I))
CVDIR IGNORE RECRDEPS
CVDIR PREFER SCALAR
CDIR$ IVDEP
      DO27J=IJU(IJL(I)),IJU(IJL(I)+1)-1
      ROW(IJU(J))=ROW(IJU(J))-ROW(IJL(I))*U(J)
27    CONTINUE
25    CONTINUE
      IF(ROW(K).EQ.0)THEN
      IERR=5
      IERR2=K
      RETURN
      ENDIF
      LD(K)=1.0D0/ROW(K)
CVDIR PREFER SCALAR
      DO29J=IJU(K),IJU(K+1)-1
      U(J)=ROW(IJU(J))*LD(K)
29    CONTINUE
17    CONTINUE
      ENDIF
      RETURN
      END
