      SUBROUTINEPCILUS(N,IJA,LEV,NZMAX,NZL,NZU,IJL,IJU,IUT,LEVL,IPT)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*),IJL(*),IJU(*),IUT(*),IPT(*),LEVL(*),LEV,
     *NZMAX,NZL,NZU
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      INTEGERIPRE1,IPRE2,RATIO
      COMMON/PCCOM3/IPRE1,IPRE2,RATIO
      SAVE/PCCOM3/
      INTEGERI,J,K,M,J1,J2,JU,NP2
      INTEGERHEAD,PREV,LM,LL,NP1,LEVP2,NZI,KK,OLV,IJAJM1,LEVLJ,
     *LEVP1
      IF(NZMAX.LT.N+1)THEN
      NZL=(IJA(N+1)-N-2)*(1+LEV)/2+N+1
      NZU=NZL
      IERR=3
      RETURN
      ENDIF
      IJL(1)=N+2
      IJU(1)=N+2
      NP1=N+1
      NZL=NP1
      NZU=NP1
      LEVP1=LEV+1
      LEVP2=LEV+2
      IF(LEV.EQ.-1)THEN
      NP2=N+2
      DO1I=2,NP1
      IJL(I)=NP2
      IJU(I)=NP2
1     CONTINUE
      RETURN
      ENDIF
      IF(LEV.EQ.0)THEN
      J2=IJA(1)
      DO3I=1,N
      J1=J2
      J2=IJA(I+1)
      JU=J2
      IF(NZL+J2-J1.GT.NZMAX)THEN
      NZL=(NZL+J2-J1)*N/I
      NZU=NZU*N/I
      IERR=3
      RETURN
      ENDIF
CVDIR PREFER SCALAR
      DO5J=J1,J2-1
      IF(IJA(J).GT.I)THEN
      JU=J
      GOTO6
      ENDIF
      NZL=NZL+1
      IJL(NZL)=IJA(J)
5     CONTINUE
6     CONTINUE
      IF(NZU+J2-JU.GT.NZMAX)THEN
      NZL=NZL*N/I
      NZU=(NZU+J2-JU)*N/I
      IERR=3
      RETURN
      ENDIF
CVDIR PREFER SCALAR
      DO7J=JU,J2-1
      NZU=NZU+1
      IJU(NZU)=IJA(J)
7     CONTINUE
      IJL(I+1)=NZL+1
      IJU(I+1)=NZU+1
3     CONTINUE
      RETURN
      ENDIF
      DO9I=1,N
      LEVL(I)=LEVP2
9     CONTINUE
      DO11I=1,N
      LEVL(I)=0
      NZI=IJA(I+1)-IJA(I)
      IF(NZI.LE.0)THEN
      IJL(I+1)=NZL+1
      IJU(I+1)=NZU+1
      ELSE
      IJAJM1=IJA(IJA(I))
      HEAD=IJAJM1
      LEVL(IJAJM1)=1
CVDIR IGNORE RECRDEPS
CVDIR PREFER SCALAR
CDIR$ IVDEP
      DO13J=IJA(I)+1,IJA(I+1)-1
      LEVL(IJA(J))=1
      IPT(IJAJM1)=IJA(J)
      IJAJM1=IJA(J)
13    CONTINUE
      IPT(IJAJM1)=NP1
      J=HEAD
      LL=0
      DO15KK=1,N
      IF(J.GE.I)THEN
      GOTO16
      ENDIF
      LL=LL+1
      LEVLJ=LEVL(J)
      IF(LEVLJ.LT.LEVP1)THEN
      PREV=J
      LM=IPT(J)
CVDIR PREFER SCALAR
      DO17M=IJU(J),IJU(J+1)-1
      OLV=LEVL(IJU(M))
      IF(LEVLJ+IUT(M).LT.OLV)THEN
      LEVL(IJU(M))=LEVLJ+IUT(M)
      IF(OLV.EQ.LEVP2)THEN
CVDIR PREFER SCALAR
      DO19K=1,N
      IF(LM.GT.IJU(M))THEN
      GOTO20
      ENDIF
      PREV=LM
      LM=IPT(LM)
19    CONTINUE
20    CONTINUE
      IPT(PREV)=IJU(M)
      IPT(IJU(M))=LM
      PREV=IJU(M)
      NZI=NZI+1
      ENDIF
      ENDIF
17    CONTINUE
      ENDIF
      J=IPT(J)
15    CONTINUE
16    CONTINUE
      NZL=NZL+LL
      IJL(I+1)=NZL+1
      NZU=NZU+NZI-LL
      IJU(I+1)=NZU+1
      IF(NZL.GT.NZMAX.OR.NZU.GT.NZMAX)THEN
      NZL=NZL*N/I
      NZU=NZU*N/I
      IERR=3
      RETURN
      ENDIF
      J=HEAD
CVDIR PREFER SCALAR
      DO21K=IJL(I),NZL
      LEVL(J)=LEVP2
      IJL(K)=J
      J=IPT(J)
21    CONTINUE
CVDIR PREFER SCALAR
      DO23K=IJU(I),NZU
      IJU(K)=J
      IUT(K)=LEVL(J)
      LEVL(J)=LEVP2
      J=IPT(J)
23    CONTINUE
      ENDIF
      LEVL(I)=LEVP2
11    CONTINUE
      RETURN
      END
