      SUBROUTINEPCILUZ(N,IJA,LEV,NZMAX,NZL,NZU,IJL,IJU,IUT,LEVL)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*),IJL(*),IJU(*),IUT(*),LEVL(*),LEV,NZMAX,
     *NZL,NZU
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      INTEGERIPRE1,IPRE2,RATIO
      COMMON/PCCOM3/IPRE1,IPRE2,RATIO
      SAVE/PCCOM3/
      INTEGERI,J,K,M,J1,J2,NP2
      INTEGERNP1,LEVP2,LEVP1,IJLM,K1,K2,IJAJ,LEVLM,IJUK,IUTK,LEVLK,
     *IJUJ
      IF(NZMAX.LT.N+1)THEN
      NZL=(IJA(N+1)-N-2)*(1+LEV)/2+N+1
      NZU=NZL
      IERR=3
      RETURN
      ENDIF
      IJL(1)=N+2
      IJU(1)=N+2
      NP1=N+1
      NZL=NP1
      NZU=NP1
      LEVP1=LEV+1
      LEVP2=LEV+2
      IF(LEV.EQ.-1)THEN
      NP2=N+2
      DO1I=2,NP1
      IJL(I)=NP2
      IJU(I)=NP2
1     CONTINUE
      RETURN
      ENDIF
      IF(LEV.EQ.0)THEN
      J2=IJA(1)
      DO3I=1,N
      J1=J2
      J2=IJA(I+1)
      IF(NZL+J2-J1.GT.NZMAX.OR.NZU+J2-J1.GT.NZMAX)THEN
      NZL=(NZL+J2-J1)*N/I
      NZU=(NZU+J2-J1)*N/I
      IERR=3
      RETURN
      ENDIF
CVDIR IGNORE RECRDEPS
CVDIR PREFER SCALAR
CDIR$ IVDEP
      DO5J=J1,J2-1
      IJAJ=IJA(J)
      IF(IJAJ.LT.I)THEN
      NZL=NZL+1
      IJL(NZL)=IJAJ
      ELSE
      NZU=NZU+1
      IJU(NZU)=IJAJ
      ENDIF
5     CONTINUE
      IJL(I+1)=NZL+1
      IJU(I+1)=NZU+1
3     CONTINUE
      CALLPCSRIJ(N,IJL,IUT)
      RETURN
      ENDIF
      DO7I=1,N
      LEVL(I)=LEVP2
7     CONTINUE
      J2=IJA(1)
      DO9I=1,N
      LEVL(I)=0
      J1=J2
      J2=IJA(I+1)
      IF(J2-J1.GT.0)THEN
      IF(MAX(NZL,NZU)+J2-J1.GT.NZMAX)THEN
      NZL=NZL*N/I
      NZU=NZU*N/I
      IERR=3
      RETURN
      ENDIF
CVDIR IGNORE RECRDEPS
CVDIR PREFER SCALAR
CDIR$ IVDEP
      DO11J=J1,J2-1
      IJAJ=IJA(J)
      LEVL(IJAJ)=1
      IF(IJAJ.LT.I)THEN
      NZL=NZL+1
      IJL(NZL)=IJAJ
      ELSE
      NZU=NZU+1
      IJU(NZU)=IJAJ
      ENDIF
11    CONTINUE
      DO13M=IJL(I),IJL(I)+N
      IF(M.GT.NZL)THEN
      GOTO14
      ENDIF
      IJLM=IJL(M)
      LEVLM=LEVL(IJLM)
      IF(LEVLM.EQ.LEVP1)THEN
      GOTO13
      ENDIF
      K1=IJU(IJLM)
      K2=IJU(IJLM+1)
      IF(MAX(NZL,NZU)+K2-K1.GT.NZMAX)THEN
      NZL=(NZL+K2-K1)*N/I
      NZU=(NZU+K2-K1)*N/I
      IERR=3
      RETURN
      ENDIF
CVDIR PREFER SCALAR
      DO15K=K1,K2-1
      IJUK=IJU(K)
      IUTK=IUT(K)
      LEVLK=LEVL(IJUK)
      IF(LEVLM+IUTK.LT.MIN(LEVLK,LEVP2))THEN
      IF(LEVLK.EQ.LEVP2)THEN
      IF(IJUK.LT.I)THEN
      NZL=NZL+1
      IJL(NZL)=IJUK
      ELSE
      NZU=NZU+1
      IJU(NZU)=IJUK
      ENDIF
      ENDIF
      LEVL(IJUK)=LEVLM+IUTK
      ENDIF
15    CONTINUE
13    CONTINUE
14    CONTINUE
      ENDIF
CVDIR PREFER SCALAR
      DO17J=IJL(I),NZL
      LEVL(IJL(J))=LEVP2
17    CONTINUE
      LEVL(I)=LEVP2
CVDIR IGNORE RECRDEPS
CVDIR PREFER SCALAR
CDIR$ IVDEP
      DO19J=IJU(I),NZU
      IJUJ=IJU(J)
      IUT(J)=LEVL(IJUJ)
      LEVL(IJUJ)=LEVP2
19    CONTINUE
      IJL(I+1)=NZL+1
      IJU(I+1)=NZU+1
9     CONTINUE
      CALLPCSRIJ(N,IJL,IUT)
      RETURN
      END
