      SUBROUTINEPCIPRM(IBLKN,IBTRM,C,X,Y)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIBLKN,IBTRM(*),C(*)
      DOUBLEPRECISIONX(*),Y(*)
      INTEGERI,YOFF,XOFF,CI,NN,ONE
      ONE=1
      XOFF=1
      DO1I=1,IBLKN
      CI=C(I)
      YOFF=IBTRM(CI)
      NN=IBTRM(CI+1)-YOFF
      CALLDCOPY(NN,X(XOFF),ONE,Y(YOFF),ONE)
      XOFF=XOFF+NN
1     CONTINUE
      RETURN
      END
