      SUBROUTINEPCIRSW(N,W,IRSW)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IRSW(*)
      DOUBLEPRECISIONW(*)
      INTEGERI,IRSWI
      DOUBLEPRECISIONT
      DO1I=1,N
      IRSWI=IRSW(I)
      IF(IRSWI.NE.I)THEN
      T=W(I)
      W(I)=W(IRSWI)
      W(IRSWI)=T
      ENDIF
1     CONTINUE
      RETURN
      END
