      SUBROUTINEPCLUB1(MODIFY,N,K,IBLKS,IBTRM,IJLB,IJUB,NI,NLI
     *,NDI,NUI,JCOL,IROW,ROW)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      LOGICALMODIFY
      INTEGERN,K,IBLKS(*),IBTRM(*),IJLB(*),IJUB(*),NI,NLI,NDI,
     *NUI,JCOL(*),IROW(*)
      DOUBLEPRECISIONROW(*)
      INTEGERRBASE,RBASEM,J,M
      RBASEM=(IBLKS(K)-1)*N
      NI=0
      IF(MODIFY)THEN
      DO1J=IJLB(K),IJLB(K+1)-1
      DO3RBASE=IBTRM(IJLB(J)),IBTRM(IJLB(J))+RBASEM,N
      CALLPC0V(IBLKS(IJLB(J)),ROW(RBASE))
3     CONTINUE
      DO5M=IBTRM(IJLB(J)),IBTRM(IJLB(J)+1)-1
      NI=NI+1
      JCOL(NI)=M
      IROW(M)=K
5     CONTINUE
1     CONTINUE
      DO7RBASE=IBTRM(K),IBTRM(K)+RBASEM,N
      CALLPC0V(IBLKS(K),ROW(RBASE))
7     CONTINUE
      NLI=NI
      NDI=NLI+1
      DO9M=IBTRM(K),IBTRM(K+1)-1
      NI=NI+1
      JCOL(NI)=M
      IROW(M)=K
9     CONTINUE
      NUI=NI+1
      DO11J=IJUB(K),IJUB(K+1)-1
      DO13RBASE=IBTRM(IJUB(J)),IBTRM(IJUB(J))+RBASEM,N
      CALLPC0V(IBLKS(IJUB(J)),ROW(RBASE))
13    CONTINUE
      DO15M=IBTRM(IJUB(J)),IBTRM(IJUB(J)+1)-1
      NI=NI+1
      JCOL(NI)=M
      IROW(M)=K
15    CONTINUE
11    CONTINUE
      ELSE
      DO17J=IJLB(K),IJLB(K+1)-1
      DO19RBASE=IBTRM(IJLB(J)),IBTRM(IJLB(J))+RBASEM,N
      CALLPC0V(IBLKS(IJLB(J)),ROW(RBASE))
19    CONTINUE
      DO21M=IBTRM(IJLB(J)),IBTRM(IJLB(J)+1)-1
      NI=NI+1
      JCOL(NI)=M
21    CONTINUE
17    CONTINUE
      DO23RBASE=IBTRM(K),IBTRM(K)+RBASEM,N
      CALLPC0V(IBLKS(K),ROW(RBASE))
23    CONTINUE
      NLI=NI
      NDI=NLI+1
      DO25M=IBTRM(K),IBTRM(K+1)-1
      NI=NI+1
      JCOL(NI)=M
25    CONTINUE
      NUI=NI+1
      DO27J=IJUB(K),IJUB(K+1)-1
      DO29RBASE=IBTRM(IJUB(J)),IBTRM(IJUB(J))+RBASEM,N
      CALLPC0V(IBLKS(IJUB(J)),ROW(RBASE))
29    CONTINUE
      DO31M=IBTRM(IJUB(J)),IBTRM(IJUB(J)+1)-1
      NI=NI+1
      JCOL(NI)=M
31    CONTINUE
27    CONTINUE
      ENDIF
      RETURN
      END
