      SUBROUTINEPCLUP1(NP1,LEV0,IROW,IJA,A,LD,HEAD,LEVL,IPT,ROW,I1,I2)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERNP1,IROW,LEVL(*),HEAD,IPT(*),IJA(*),LEV0,I1,I2
      DOUBLEPRECISIONA(*),ROW(*),LD(*)
      INTEGERISRT,IJASGN,ISX0,IFORM
      COMMON/PCVERI/ISRT,IJASGN,ISX0,IFORM
      SAVE/PCVERI/
      INTEGERJ,J1,J2,KK,IJAJ,LEV1
      J1=IJA(IROW)
      J2=IJA(IROW+1)-1
      LEV1=LEV0+1
      HEAD=NP1
      DO1J=I1,I2
      ROW(J)=0.0D0
 1    CONTINUE
      IF(J2.GE.J1)THEN
      KK=0
      DO7J=J1,J2
      IJAJ=IJA(J)
      ROW(IJAJ)=A(J)
      KK=KK+1
      LEVL(KK)=IJAJ
7     CONTINUE
      IF(ISRT.NE.1)CALLPCSRTI(KK,LEVL)
      DO9J=KK,1,-1
      IJAJ=LEVL(J)
      LEVL(IJAJ)=LEV1
      IPT(IJAJ)=HEAD
      HEAD=IJAJ
9     CONTINUE
      ENDIF
      LEVL(IROW)=LEV0
      ROW(IROW)=LD(IROW)
      RETURN
      END
