      SUBROUTINEPCMLIC(N,IJL,L,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJL(*)
      DOUBLEPRECISIONW(*),L(*)
      INTEGERI,J1,J2,J
      DOUBLEPRECISIONWI
      J2=IJL(1)
      DO1I=1,N-1
      J1=J2
      J2=IJL(I+1)
      WI=W(I)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO3J=J1,J2-1
      W(IJL(J))=W(IJL(J))-WI*L(J)
3     CONTINUE
1     CONTINUE
      RETURN
      END
