      SUBROUTINEPCMLIR(N,IJL,LD,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJL(*)
      DOUBLEPRECISIONW(*),LD(*)
      INTEGERI,J1,J2,J
      DOUBLEPRECISIONSUM
      J2=IJL(1)
      DO1I=1,N
      SUM=W(I)
      J1=J2
      J2=IJL(I+1)
CVDIR PREFER SCALAR
      DO3J=J1,J2-1
      SUM=SUM-LD(J)*W(IJL(J))
3     CONTINUE
      W(I)=SUM
1     CONTINUE
      RETURN
      END
