      SUBROUTINEPCMLC(N,IJL,L,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJL(*)
      DOUBLEPRECISIONW(*),L(*)
      INTEGERI,J1,J2,J
      DOUBLEPRECISIONWI
      J1=IJL(N)
      DO1I=N-1,1,-1
      J2=J1
      J1=IJL(I)
      WI=W(I)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO3J=J1,J2-1
      W(IJL(J))=W(IJL(J))+WI*L(J)
3     CONTINUE
1     CONTINUE
      RETURN
      END
