      SUBROUTINEPCMUC(N,IJU,U,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJU(*)
      DOUBLEPRECISIONW(*),U(*)
      INTEGERI,J1,J2,J
      DOUBLEPRECISIONWI
      J2=IJU(2)
      DO1I=2,N
      WI=W(I)
      J1=J2
      J2=IJU(I+1)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO3J=J1,J2-1
      W(IJU(J))=W(IJU(J))+WI*U(J)
3     CONTINUE
1     CONTINUE
      RETURN
      END
