      SUBROUTINEPCMUIC(N,IJU,U,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJU(*)
      DOUBLEPRECISIONW(*),U(*)
      INTEGERI,J1,J2,J
      DOUBLEPRECISIONWI
      J1=IJU(N+1)
      DO1I=N,2,-1
      J2=J1
      J1=IJU(I)
      WI=W(I)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO3J=J2-1,J1,-1
      W(IJU(J))=W(IJU(J))-WI*U(J)
3     CONTINUE
1     CONTINUE
      RETURN
      END
