      SUBROUTINEPCPAXP(N,IJA,S,V,A)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*)
      DOUBLEPRECISIONS,A(*),V(*)
      INTEGERK
      DO1K=1,N
      A(IJA(K))=A(IJA(K))+S*V(IJA(K))
1     CONTINUE
      RETURN
      END
