      SUBROUTINEPCPACK(IPARM,RPARM)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIPARM(*)
      DOUBLEPRECISIONRPARM(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      DOUBLEPRECISIONACCEL,RESID,ACC2
      COMMON/PCCOM2/ACCEL,RESID,ACC2
      SAVE/PCCOM2/
      INTEGERISTOP,IRESD,INORM,ISAME,ISTATP,IRSDS,IOUT,JOUT,ISTATS,
     *ISTAT1,ISTAT2
      DOUBLEPRECISIONEPS1,EPS2
      COMMON/PCSTIC/ISTOP,IRESD,INORM,ISAME,ISTATP,IRSDS,IOUT,JOUT,
     *ISTATS,ISTAT1,ISTAT2
      COMMON/PCSTRC/EPS1,EPS2
      SAVE/PCSTIC/,/PCSTRC/
      
C	  Added to specify if ILU is computed
	  integer bLUcomputed
	  common/VCELL/ bLUcomputed
	  save/VCELL/
      
      IF(IPARM(1).LT.200)THEN
      IPARM(1)=IERR
      IPARM(12)=MNEED
      IPARM(13)=ITS
      ELSE
      IPARM(51)=IERR
      IPARM(52)=IERR2
      IPARM(53)=ITS
      IPARM(54)=MNEED
      IPARM(61)=IRSDS
      
C	  Added to specify if ILU is computed
C 	  write (6,*), "bLUcomputed=",bLUcomputed      
      IPARM(55) = bLUcomputed
      
      RPARM(21)=RESID
      ENDIF
      RETURN
      END
