      SUBROUTINEPCPCSF(N,IJA,IJAR,LINKA,LEV,NZMAX,NZU,IJU,IUT,JL,IFC,
     *LEVL,IPT)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*),IJAR(*),LINKA(*),LEV,NZMAX,NZU,IJU(*),
     *IUT(*),JL(*),IFC(*),LEVL(*),IPT(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT,PROCNO,
     *RDRIV,RMETH,RPREC,RMVP,RENDR,RITM,RFILL,RKMAX,SCMETH,
     *SCPREC,SCMVP,SCKMAX,SCITM,NX,NY,NZ,PX,PY,PZ
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT,PROCNO,RDRIV,RMETH,RPREC,RMVP,RENDR,RITM,RFILL,
     *RKMAX,SCMETH,SCPREC,SCMVP,SCKMAX,SCITM,NX,NY,NZ,PX,PY,PZ
      SAVE/PCCOM1/
      INTEGERIPRE1,IPRE2,RATIO
      COMMON/PCCOM3/IPRE1,IPRE2,RATIO
      SAVE/PCCOM3/
      INTEGERISRT,IJASGN,ISX0,IFORM
      COMMON/PCVERI/ISRT,IJASGN,ISX0,IFORM
      SAVE/PCVERI/
      LOGICALLOWER,UPPER,FULL,HALF
      COMMON/PCVERL/LOWER,UPPER,FULL,HALF
      SAVE/PCVERL/
      INTEGERI,J,K,M,MM
      INTEGERPREV,LM,NP1,LEVP2,OLV,J1,J2,JU1,JU2,LUI,IPTM,
     *ELV,KLK,LEVP1,KNEXT,IJAJ
      IF(LEV.EQ.-1)THEN
      NZU=N+1
      IF(NZMAX.LT.N+1)THEN
      IERR=3
      RETURN
      ENDIF
      DO1I=1,N+1
      IJU(I)=N+2
1     CONTINUE
      RETURN
      ENDIF
      IF(LEV.EQ.0)THEN
      IF(UPPER)THEN
      NZU=IJA(N+1)-1
      IF(NZMAX.LT.NZU)THEN
      IERR=3
      RETURN
      ENDIF
      CALLPCICPY(IJA(N+1)-1,IJA,IJU)
      ELSEIF(LOWER)THEN
      NZU=IJA(N+1)-1
      IF(NZMAX.LT.NZU)THEN
      IERR=3
      RETURN
      ENDIF
      CALLPCSRIZ(N,IJA,IJU)
      CALLPCSRIX(N,IJA,IJU)
      ELSE
      J2=IJA(1)
      IJU(1)=N+2
      NZU=N+1
      DO3I=1,N
      J1=J2
      J2=IJA(I+1)
      DO5J=J1,J2-1
      IF(IJA(J).LT.I)THEN
      GOTO5
      ENDIF
      NZU=NZU+1
      IF(NZMAX.LT.NZU)THEN
      NZU=N*NZU/I
      IERR=3
      RETURN
      ENDIF
      IJU(NZU)=IJA(J)
5     CONTINUE
      IJU(I+1)=NZU+1
3     CONTINUE
      ENDIF
      IF((UPPER.OR.FULL).AND.ISRT.EQ.0)THEN
      CALLPCSRIJ(N,IJU,IUT)
      ENDIF
      RETURN
      ENDIF
      IJU(1)=N+2
      NP1=N+1
      NZU=NP1
      LEVP2=LEV+2
      LEVP1=LEV+1
      DO7I=1,N
      JL(I)=0
      LEVL(I)=LEVP2
7     CONTINUE
      J2=IJA(1)
      DO9I=1,N
      LEVL(I)=0
      IPT(I)=NP1
      IF(LOWER)THEN
      J=I
      PREV=I
      LUI=0
      DO11K=1,N
      J=LINKA(J)
      IF(J.EQ.0)THEN
      GOTO12
      ENDIF
      LUI=LUI+1
      IPT(PREV)=IJAR(J)
      PREV=IJAR(J)
      LEVL(PREV)=1
11    CONTINUE
12    CONTINUE
      IPT(PREV)=NP1
      ELSEIF(UPPER)THEN
      J1=J2
      J2=IJA(I+1)
      IF(ISRT.EQ.0)THEN
      DO13J=J1,J2-1
      IPTM=I
      DO15K=1,N
      M=IPTM
      IPTM=IPT(M)
      IF(IPTM.GT.IJA(J))THEN
      GOTO16
      ENDIF
15    CONTINUE
16    CONTINUE
      IPT(M)=IJA(J)
      IPT(IJA(J))=IPTM
      LEVL(IJA(J))=1
13    CONTINUE
      ELSE
      PREV=I
      DO17J=J1,J2-1
      IPT(PREV)=IJA(J)
      PREV=IJA(J)
      LEVL(PREV)=1
17    CONTINUE
      IPT(PREV)=NP1
      ENDIF
      LUI=J2-J1
      ELSE
      J1=J2
      J2=IJA(I+1)
      LUI=0
      IF(ISRT.EQ.0)THEN
      DO19J=J1,J2-1
      IF(IJA(J).LT.I)THEN
      GOTO19
      ENDIF
      LUI=LUI+1
      IPTM=I
      DO21K=1,N
      M=IPTM
      IPTM=IPT(M)
      IF(IPTM.GT.IJA(J))THEN
      GOTO22
      ENDIF
21    CONTINUE
22    CONTINUE
      IPT(M)=IJA(J)
      IPT(IJA(J))=IPTM
      LEVL(IJA(J))=1
19    CONTINUE
      ELSE
      PREV=I
      DO23J=J1,J2-1
      IF(IJA(J).LT.I)THEN
      GOTO23
      ENDIF
      LUI=LUI+1
      IPT(PREV)=IJA(J)
      PREV=IJA(J)
      LEVL(PREV)=1
23    CONTINUE
      IPT(PREV)=NP1
      ENDIF
      ENDIF
      NZU=NZU+LUI
      K=I
      K=JL(K)
      DO25M=1,N
      IF(K.EQ.0)THEN
      GOTO26
      ENDIF
      KNEXT=JL(K)
      JU2=IJU(K+1)-1
      KLK=IFC(K)
      JU1=KLK+1
      ELV=IUT(KLK)
      IF(ELV.NE.LEVP1)THEN
      PREV=I
      IF(JU1.LE.JU2)THEN
      DO27J=JU1,JU2
      OLV=LEVL(IJU(J))
      IF(ELV+IUT(J).LT.OLV)THEN
      LEVL(IJU(J))=ELV+IUT(J)
      IF(OLV.EQ.LEVP2)THEN
      LM=IPT(PREV)
      DO29MM=1,N
      IF(IJU(J).LT.LM)THEN
      GOTO30
      ENDIF
      PREV=LM
      LM=IPT(LM)
29    CONTINUE
30    CONTINUE
      IPT(PREV)=IJU(J)
      IPT(IJU(J))=LM
      PREV=IJU(J)
      NZU=NZU+1
      ENDIF
      ENDIF
27    CONTINUE
      IFC(K)=JU1
      J=IJU(JU1)
      JL(K)=JL(J)
      JL(J)=K
      ENDIF
      ENDIF
      K=KNEXT
25    CONTINUE
26    CONTINUE
      IJU(I+1)=NZU+1
      IF(NZU.GT.NZMAX)THEN
      NZU=NZU*N/I
      IERR=3
      RETURN
      ENDIF
      J=IPT(I)
      DO31K=IJU(I),NZU
      IUT(K)=LEVL(J)
      LEVL(J)=LEVP2
      IJU(K)=J
      J=IPT(J)
31    CONTINUE
      LEVL(I)=LEVP2
      IF(IJU(I).NE.IJU(I+1))THEN
      IFC(I)=IJU(I)
      K=IJU(IJU(I))
      JL(I)=JL(K)
      JL(K)=I
      ENDIF
9     CONTINUE
      RETURN
      END
