      SUBROUTINEPCPCNF(MODIFY,N,IJA,IJAR,LINKA,IJU,A,UD,JL,
     *IFC,MARK,ROW)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      LOGICALMODIFY
      INTEGERN,IJA(*),IJAR(*),LINKA(*),IFC(*),IJU(*),JL(*),MARK(*
     *)
      DOUBLEPRECISIONA(*),UD(*),ROW(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT,PROCNO,
     *RDRIV,RMETH,RPREC,RMVP,RENDR,RITM,RFILL,RKMAX,SCMETH,
     *SCPREC,SCMVP,SCKMAX,SCITM,NX,NY,NZ,PX,PY,PZ
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT,PROCNO,RDRIV,RMETH,RPREC,RMVP,RENDR,RITM,RFILL,
     *RKMAX,SCMETH,SCPREC,SCMVP,SCKMAX,SCITM,NX,NY,NZ,PX,PY,PZ
      SAVE/PCCOM1/
      DOUBLEPRECISIONACCEL,RESID,ACC2
      COMMON/PCCOM2/ACCEL,RESID,ACC2
      SAVE/PCCOM2/
      LOGICALLOWER,UPPER,FULL,HALF
      COMMON/PCVERL/LOWER,UPPER,FULL,HALF
      SAVE/PCVERL/
      INTEGERI,J,K,ONE,M,IJU1,IJU2,IJA1,IJA2,NEXTI,ILI,J1,
     *J2,IJUJ
      DOUBLEPRECISIONDK,UKIDI,TM1,TM2
      ONE=1
      CALLDCOPY(N,A,ONE,UD,ONE)
      IF(ACCEL.NE.0.0D0)THEN
      DO1I=1,N
      UD(I)=UD(I)+ACCEL
1     CONTINUE
      ENDIF
      IF(MODIFY)THEN
      CALLPC0VI(N,MARK)
      ENDIF
      CALLPC0VI(N,JL)
      IJU2=IJU(1)
      IJA2=IJA(1)
      DO3K=1,N
      IJU1=IJU2
      IJU2=IJU(K+1)
      IF(MODIFY)THEN
      DO5J=IJU1,IJU2-1
      IJUJ=IJU(J)
      MARK(IJUJ)=K
      ROW(IJUJ)=0.0D0
5     CONTINUE
      ELSE
      DO7J=IJU1,IJU2-1
      ROW(IJU(J))=0.0D0
7     CONTINUE
      ENDIF
      ROW(K)=UD(K)
      IJA1=IJA2
      IJA2=IJA(K+1)
      IF(UPPER)THEN
      DO9J=IJA1,IJA2-1
      ROW(IJA(J))=A(J)
9     CONTINUE
      ELSEIF(FULL)THEN
      DO11J=IJA1,IJA2-1
      IF(IJA(J).GT.K)THEN
      ROW(IJA(J))=A(J)
      ENDIF
11    CONTINUE
      ELSEIF(LOWER)THEN
      J=LINKA(K)
      DO13M=1,N
      IF(J.EQ.0)THEN
      GOTO14
      ENDIF
      ROW(IJAR(J))=A(J)
      J=LINKA(J)
13    CONTINUE
14    CONTINUE
      ENDIF
      DK=UD(K)
      I=JL(K)
      DO15M=1,N
      IF(I.EQ.0)THEN
      GOTO16
      ENDIF
      NEXTI=JL(I)
      ILI=IFC(I)
      UKIDI=-UD(ILI)*UD(I)
      DK=DK+UKIDI*UD(ILI)
      UD(ILI)=-UKIDI
      TM1=UKIDI*ACC2
      J1=ILI+1
      J2=IJU(I+1)-1
      IF(J1.LE.J2)THEN
      IF(MODIFY)THEN
      DO17J=J1,J2
      IJUJ=IJU(J)
      IF(MARK(IJUJ).EQ.K)THEN
      ROW(IJUJ)=ROW(IJUJ)+UKIDI*UD(J)
      ELSE
      TM2=TM1*UD(J)
      DK=DK+TM2
      UD(IJUJ)=UD(IJUJ)+TM2
      ENDIF
17    CONTINUE
      ELSE
      DO19J=J1,J2
      IJUJ=IJU(J)
      ROW(IJUJ)=ROW(IJUJ)+UKIDI*UD(J)
19    CONTINUE
      ENDIF
      IFC(I)=J1
      J=IJU(J1)
      JL(I)=JL(J)
      JL(J)=I
      ENDIF
      I=NEXTI
15    CONTINUE
16    CONTINUE
      IF(DK.EQ.0.0D0)THEN
      IERR=5
      IERR2=K
      RETURN
      ENDIF
      UD(K)=1.0D0/DK
      DO21I=IJU1,IJU2-1
      UD(I)=ROW(IJU(I))
21    CONTINUE
      IF(IJU(K).NE.IJU(K+1))THEN
      IFC(K)=IJU(K)
      I=IJU(IJU(K))
      JL(K)=JL(I)
      JL(I)=K
      ENDIF
3     CONTINUE
      RETURN
      END
