      SUBROUTINEPCPUNP(N,IPARM,RPARM,IERRP,IERR2P)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IPARM(*),IERRP,IERR2P
      DOUBLEPRECISIONRPARM(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      IERRP=0
      IERR2P=0
 1000 CONTINUE
      RETURN
      END
