      SUBROUTINEPCRC1B(IBLKN,IBTRM,IRTBM,NBLCKB,C,IC,IJA,A,V,
     *W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIBLKN,IBTRM(*),IRTBM(*),NBLCKB,C(*),IC(*),IJA(*)
      DOUBLEPRECISIONA(*),V(*),W(*)
      INTEGERI,II,J,K,IP
      DOUBLEPRECISIONSUM
      IP=0
      DO1I=1,NBLCKB
      II=C(I)
      DO3J=IBTRM(II),IBTRM(II+1)-1
      SUM=V(J)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO5K=IJA(J),IJA(J+1)-1
      IF(NBLCKB.LT.IC(IRTBM(IJA(K))))THEN
      SUM=SUM-A(K)*V(IJA(K))
      ENDIF
5     CONTINUE
      IP=IP+1
      W(IP)=SUM
3     CONTINUE
1     CONTINUE
      RETURN
      END
