      SUBROUTINEPCRC1P(NBLACK,N,C,IC,IJA,A,V1,V2)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERNBLACK,N,C(*),IC(*),IJA(*)
      DOUBLEPRECISIONA(*),V1(*),V2(*)
      INTEGERI,II,K,RC
      DOUBLEPRECISIONSUM
      DO1I=1,NBLACK
      II=C(I)
      SUM=0.0D0
      DO3K=IJA(II),IJA(II+1)-1
      RC=IC(IJA(K))-NBLACK
      IF(RC.GT.0)THEN
      SUM=SUM+A(K)*V1(RC)
      ENDIF
3     CONTINUE
      V2(I)=V2(I)-SUM
1     CONTINUE
      RETURN
      END
