      SUBROUTINEPCRCPR(N,A,B)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN
      DOUBLEPRECISIONA(*),B(*)
      INTEGERI
      DO1I=N,1,-1
      B(I)=A(I)
1     CONTINUE
      RETURN
      END
