      SUBROUTINEPCRC2B(IBLKN,IBTRM,IRTBM,IBTRMC,NBLCKB,C,IC,IJA
     *,A,V)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIBLKN,IBTRM(*),IRTBM(*),IBTRMC(*),NBLCKB,C(*),
     *IC(*),IJA(*)
      DOUBLEPRECISIONA(*),V(*)
      INTEGERI,II,J,K,BCOL,RAWBCL
      DOUBLEPRECISIONSUM
      DO1I=NBLCKB+1,IBLKN
      II=C(I)
      DO3J=IBTRM(II),IBTRM(II+1)-1
      SUM=V(J)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO5K=IJA(J),IJA(J+1)-1
      RAWBCL=IRTBM(IJA(K))
      BCOL=IC(RAWBCL)
      IF(BCOL.LE.NBLCKB)THEN
      SUM=SUM-A(K)*V(IJA(K))
      ENDIF
5     CONTINUE
      V(J)=SUM
3     CONTINUE
1     CONTINUE
      RETURN
      END
