      SUBROUTINEPCRSBS(IBLKN,NBLCKB,IJRSB,NZRSMX,IBTRMC,IJRS,NZRS)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIBLKN,NBLCKB,IJRSB(*),NZRSMX,IBTRMC(*),IJRS(*),NZRS
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      INTEGERID,ICUR,NI,I,J,JJ,K,MM,NBLACK
      NBLACK=IBTRMC(NBLCKB+1)-1
      NZRS=NBLACK+1
      MM=1
      IJRS(1)=NBLACK+2
      DO1I=1,NBLCKB
      ICUR=NZRS+1
      DO3J=IJRSB(I),IJRSB(I+1)-1
      JJ=IJRSB(J)
      IF(NZRS+IBTRMC(JJ+1)-IBTRMC(JJ).GT.NZRSMX)THEN
      NZRSMX=(NZRS+IBTRMC(JJ+1)-IBTRMC(JJ))*(NBLCKB-I)/I
      IERR=10
      RETURN
      ENDIF
      DO5K=IBTRMC(JJ),IBTRMC(JJ+1)-1
      NZRS=NZRS+1
      IJRS(NZRS)=K
5     CONTINUE
3     CONTINUE
      ID=NZRS
      IF(NZRS+IBTRMC(I+1)-IBTRMC(I)-1.GT.NZRSMX)THEN
      NZRSMX=(NZRS+IBTRMC(I+1)-IBTRMC(I)-1)*(NBLCKB-I)/I
      IERR=10
      RETURN
      ENDIF
      DO7J=IBTRMC(I)+1,IBTRMC(I+1)-1
      NZRS=NZRS+1
      IJRS(NZRS)=J
7     CONTINUE
      NI=NZRS+1-ICUR
      MM=MM+1
      IJRS(MM)=NZRS+1
      IF(NZRS+(IBTRMC(I+1)-IBTRMC(I)-1)*NI.GT.NZRSMX)THEN
      NZRSMX=NZRSMX*(NBLCKB-I+1)/I
      IERR=10
      RETURN
      ENDIF
      DO9J=IBTRMC(I)+1,IBTRMC(I+1)-1
      CALLPCICPY(NI,IJRS(ICUR),IJRS(NZRS+1))
      ID=ID+NI+1
      IJRS(ID)=IJRS(ID)-1
      ICUR=ICUR+NI
      NZRS=NZRS+NI
      MM=MM+1
      IJRS(MM)=NZRS+1
9     CONTINUE
1     CONTINUE
      RETURN
      END
