      SUBROUTINEPCRSFM(N,IBLKN,IBLKS,IBTRM,IRTBM,IBTRMC,NBLCKB,
     *NBLACK,C,IC,CP,IJA,IJAB,ID2I,IPVT,NZRS,IJRS,A,RHS,D2I
     *,RSRHS,RS,ROW,C1DI)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IBLKN,IBLKS(*),IBTRM(*),IRTBM(*),IBTRMC(*),
     *NBLCKB,NBLACK,C(*),IC(*),CP(*),IJA(*),IJAB(*),
     *ID2I(*),IPVT(*),NZRS,IJRS(*)
      DOUBLEPRECISIONA(*),RHS(*),D2I(*),RS(*),RSRHS(*),
     *ROW(*),C1DI(*)
      INTEGERI,J,K,L,M1,M2,J1,J2,IJABJ,ELMROW,BCOL,ROWCNT,
     *ONE,COLOFF,NC
      DOUBLEPRECISIONDDOT
      ONE=1
      CALLPCPRMB(NBLCKB,IBTRM,C,RHS,RSRHS)
      ROWCNT=0
      DO1I=1,NBLCKB
      ELMROW=C(I)
      DO3K=IBTRM(ELMROW),IBTRM(ELMROW+1)-1
      ROWCNT=ROWCNT+1
      DO5J=IJRS(ROWCNT),IJRS(ROWCNT+1)-1
      ROW(CP(IJRS(J)))=0.0D0
5     CONTINUE
      DO7J=IJAB(ELMROW),IJAB(ELMROW+1)-1
      DO9L=IBTRM(IJAB(J)),IBTRM(IJAB(J)+1)-1
      ROW(L)=0.0D0
9     CONTINUE
7     CONTINUE
      J1=IJA(K)
      J2=IJA(K+1)-1
      DO11J=J1,J2
      ROW(IJA(J))=A(J)
11    CONTINUE
      ROW(K)=A(K)
      DO13J=IJAB(ELMROW),IJAB(ELMROW+1)-1
      IJABJ=IJAB(J)
      BCOL=IC(IJABJ)
      IF(BCOL.LE.NBLCKB)THEN
      GOTO13
      ENDIF
      COLOFF=IBTRM(IJABJ)
      NC=IBLKS(IJABJ)
      CALLPCD2IT(NC,NC,IPVT(IBTRMC(BCOL)-NBLACK),D2I(ID2I(
     *BCOL-NBLCKB)),ROW(COLOFF),C1DI)
      RSRHS(ROWCNT)=RSRHS(ROWCNT)-DDOT(NC,C1DI,ONE,RHS(
     *COLOFF),ONE)
      M2=IJA(COLOFF)
      DO15L=COLOFF,COLOFF+NC-1
      M1=M2
      M2=IJA(L+1)
      CALLPCAXPY(M2-M1,IJA(M1),-C1DI(L+1-COLOFF),A(M1),ROW
     *)
15    CONTINUE
13    CONTINUE
      DO17J=IJRS(ROWCNT),IJRS(ROWCNT+1)-1
      RS(J)=ROW(CP(IJRS(J)))
17    CONTINUE
      RS(ROWCNT)=ROW(K)
3     CONTINUE
1     CONTINUE
      RETURN
      END
