      SUBROUTINEPCRSPF(N,NBLACK,C,IC,IJA,IJRS,A,RHS,D2I,RSRHS
     *,RS,ROW)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NBLACK,C(*),IC(*),IJA(*),IJRS(*)
      DOUBLEPRECISIOND2I(*),RS(*),ROW(*),RSRHS(*),A(*),RHS(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      INTEGERI,J,K,L,BCOL,IJAL,M
      DOUBLEPRECISIOND
      DO1I=NBLACK+1,N
      D=A(C(I))
      IF(D.EQ.0.0D0)THEN
      IERR=11
      IERR2=C(I)
      RETURN
      ENDIF
      D2I(I-NBLACK)=1.0D0/D
1     CONTINUE
      DO3I=1,NBLACK
      K=C(I)
      RSRHS(I)=RHS(K)
      DO5M=IJRS(I),IJRS(I+1)-1
      ROW(C(IJRS(M)))=0.0D0
5     CONTINUE
      ROW(K)=A(K)
      DO7L=IJA(K),IJA(K+1)-1
      ROW(IJA(L))=A(L)
7     CONTINUE
      DO9L=IJA(K),IJA(K+1)-1
      IJAL=IJA(L)
      BCOL=IC(IJAL)-NBLACK
      IF(BCOL.GT.0)THEN
      D=A(L)*D2I(BCOL)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO11J=IJA(IJAL),IJA(IJAL+1)-1
      ROW(IJA(J))=ROW(IJA(J))-A(J)*D
11    CONTINUE
      RSRHS(I)=RSRHS(I)-D*RHS(IJAL)
      ENDIF
9     CONTINUE
      DO13M=IJRS(I),IJRS(I+1)-1
      RS(M)=ROW(C(IJRS(M)))
13    CONTINUE
      RS(I)=ROW(K)
3     CONTINUE
      RETURN
      END
