      SUBROUTINEPCRSRB(IBLKN,IBLKS,IBTRM,IJAB,ND2I,NBLCKB,NBLACK
     *,P,IP,IBTRMC,CP)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIBLKN,IBLKS(*),IBTRM(*),NBLCKB,IJAB(*),ND2I,P(*),
     *IP(*),CP(*),NBLACK,IBTRMC(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      INTEGERI,L,J
      IF(RED1.NE.0.AND.RED2.NE.0)THEN
      IF(RED1.GT.IBLKN)THEN
      IERR=16
      IERR2=16
      RETURN
      ELSEIF(RED2.GT.IBLKN)THEN
      IERR=16
      IERR2=17
      RETURN
      ENDIF
      CALLPCCRED(IBLKN,IJAB,NBLCKB,P,IP,CP)
      IF(IERR.NE.0)RETURN
      ELSE
      CALLPCRSRP(IBLKN,IJAB,NBLCKB,P,IP,CP)
      ENDIF
      NBLACK=0
      ND2I=0
      IBTRMC(1)=1
      DO1L=1,NBLCKB
      IBTRMC(L+1)=IBTRMC(L)+IBLKS(P(L))
      NBLACK=NBLACK+IBLKS(P(L))
1     CONTINUE
      DO3L=NBLCKB+1,IBLKN
      IBTRMC(L+1)=IBTRMC(L)+IBLKS(P(L))
      ND2I=ND2I+IBLKS(P(L))*IBLKS(P(L))
3     CONTINUE
      I=0
      DO5L=1,NBLCKB
      DO7J=IBTRM(P(L)),IBTRM(P(L)+1)-1
      I=I+1
      CP(I)=J
7     CONTINUE
5     CONTINUE
      RETURN
      END
