      SUBROUTINEPCRSAD(NBLCKB,IBLKN,IBTRMC,IJRS)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERNBLCKB,IBLKN,IBTRMC(*),IJRS(*)
      INTEGERI,J
      DO1I=1,NBLCKB
      DO3J=IBTRMC(I)+1,IBTRMC(I+1)-1
      IJRS(J)=-IJRS(J)
3     CONTINUE
1     CONTINUE
      RETURN
      END
