      SUBROUTINEPCSBGE(N,IBLKN,IBLKS,IBTRM,IRTBM,IBTRMC,NBLCKB,
     *NBLACK,C,IC,CP,IJA,LINK,IPTR,IJAB,IJABP,ID2I,NZRS,IJRS
     *,A,RHS,D2I,RSRHS,RS,ROW,C1DI)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IBLKN,IBLKS(*),IBTRM(*),IRTBM(*),IBTRMC(*),
     *NBLCKB,NBLACK,C(*),IC(*),CP(*),IJA(*),LINK(*),
     *IPTR(*),IJAB(*),IJABP(*),ID2I(*),NZRS,IJRS(*)
      DOUBLEPRECISIONA(*),RHS(*),D2I(*),RS(*),RSRHS(*),ROW(*)
     *,
     *C1DI(*)
      LOGICALLOWER,UPPER,FULL,HALF,SYMMAT
      COMMON/PCVERL/LOWER,UPPER,FULL,HALF,SYMMAT
      SAVE/PCVERL/
      INTEGERI,J,K,L,M1,M2,IJABJ,M,ELMROW,BCOL,ROWCNT,
     *ONE,COLOFF,NC,HD
      DOUBLEPRECISIONDDOT
      ONE=1
      CALLPCPRMB(NBLCKB,IBTRM,C,RHS,RSRHS)
      ROWCNT=0
      DO1I=1,NBLCKB
      ELMROW=C(I)
      DO3K=IBTRM(ELMROW),IBTRM(ELMROW+1)-1
      ROWCNT=ROWCNT+1
      DO5J=IJRS(ROWCNT),IJRS(ROWCNT+1)-1
      ROW(CP(IJRS(J)))=0.0D0
5     CONTINUE
      DO7J=IJAB(ELMROW),IJAB(ELMROW+1)-1
      DO9L=IBTRM(IJAB(J)),IBTRM(IJAB(J)+1)-1
      ROW(L)=0.0D0
9     CONTINUE
7     CONTINUE
      IF(HALF)THEN
      DO11J=IJABP(ELMROW),IJABP(ELMROW+1)-1
      DO13L=IBTRM(IJABP(J)),IBTRM(IJABP(J)+1)-1
      ROW(L)=0.0D0
13    CONTINUE
11    CONTINUE
      ENDIF
      DO15J=IJA(K),IJA(K+1)-1
      ROW(IJA(J))=A(J)
15    CONTINUE
      IF(HALF)THEN
      HD=LINK(K)
      DO17J=1,N
      IF(HD.EQ.0)THEN
      GOTO18
      ENDIF
      ROW(IPTR(HD))=A(HD)
      HD=LINK(HD)
17    CONTINUE
18    CONTINUE
      ENDIF
      ROW(K)=A(K)
      DO19J=IJAB(ELMROW),IJAB(ELMROW+1)-1
      IJABJ=IJAB(J)
      BCOL=IC(IJABJ)
      IF(BCOL.LE.NBLCKB)THEN
      GOTO19
      ENDIF
      COLOFF=IBTRM(IJABJ)
      NC=IBLKS(IJABJ)
      CALLDCOPY(NC,ROW(COLOFF),ONE,C1DI,ONE)
      CALLPCSPSL(NC,NC,D2I(ID2I(BCOL-NBLCKB)),C1DI)
      RSRHS(ROWCNT)=RSRHS(ROWCNT)-DDOT(NC,C1DI,ONE,RHS(
     *COLOFF),ONE)
      M2=IJA(COLOFF)
      DO21L=COLOFF,COLOFF+NC-1
      M1=M2
      M2=IJA(L+1)
      CALLPCAXPY(M2-M1,IJA(M1),-C1DI(L+1-COLOFF),A(M1),ROW)
      IF(HALF)THEN
      HD=LINK(L)
      DO23M=1,N
      IF(HD.EQ.0)THEN
      GOTO24
      ENDIF
      ROW(IPTR(HD))=ROW(IPTR(HD))-C1DI(L+1-COLOFF
     *)*A(HD)
      HD=LINK(HD)
23    CONTINUE
24    CONTINUE
      ENDIF
21    CONTINUE
19    CONTINUE
      IF(HALF)THEN
      DO25J=IJABP(ELMROW),IJABP(ELMROW+1)-1
      IJABJ=IJABP(J)
      BCOL=IC(IJABJ)
      IF(BCOL.LE.NBLCKB)THEN
      GOTO25
      ENDIF
      COLOFF=IBTRM(IJABJ)
      NC=IBLKS(IJABJ)
      CALLDCOPY(NC,ROW(COLOFF),ONE,C1DI,ONE)
      CALLPCSPSL(NC,NC,D2I(ID2I(BCOL-NBLCKB)),C1DI)
      RSRHS(ROWCNT)=RSRHS(ROWCNT)-DDOT(NC,C1DI,ONE,RHS(
     *COLOFF),ONE)
      M2=IJA(COLOFF)
      DO27L=COLOFF,COLOFF+NC-1
      M1=M2
      M2=IJA(L+1)
      CALLPCAXPY(M2-M1,IJA(M1),-C1DI(L+1-COLOFF),A(M1),
     *ROW)
      HD=LINK(L)
      DO29M=1,N
      IF(HD.EQ.0)THEN
      GOTO30
      ENDIF
      ROW(IPTR(HD))=ROW(IPTR(HD))-C1DI(L+1-COLOFF
     *)*A(HD)
      HD=LINK(HD)
29    CONTINUE
30    CONTINUE
27    CONTINUE
25    CONTINUE
      ENDIF
      DO31J=IJRS(ROWCNT),IJRS(ROWCNT+1)-1
      RS(J)=ROW(CP(IJRS(J)))
31    CONTINUE
      RS(ROWCNT)=ROW(K)
3     CONTINUE
1     CONTINUE
      RETURN
      END
