      SUBROUTINEPCSBGP(N,NBLACK,C,IC,IJA,LINK,IPTR,IJRS,A,RHS
     *,D2I,RSRHS,RS,ROW)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NBLACK,C(*),IC(*),IJA(*),LINK(*),IPTR(*),IJRS(*)
      DOUBLEPRECISIOND2I(*),RS(*),ROW(*),RSRHS(*),A(*),RHS(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      LOGICALLOWER,UPPER,FULL,HALF,SYMMAT
      COMMON/PCVERL/LOWER,UPPER,FULL,HALF,SYMMAT
      SAVE/PCVERL/
      INTEGERI,J,K,L,BCOL,IJAL,M,HD,HDO
      DOUBLEPRECISIOND
      DO1I=NBLACK+1,N
      D=A(C(I))
      IF(D.EQ.0.0D0)THEN
      IERR=11
      IERR2=C(I)
      RETURN
      ENDIF
      D2I(I-NBLACK)=1.0D0/D
1     CONTINUE
      DO3I=1,NBLACK
      K=C(I)
      RSRHS(I)=RHS(K)
      DO5M=IJRS(I),IJRS(I+1)-1
      ROW(C(IJRS(M)))=0.0D0
5     CONTINUE
      ROW(K)=A(K)
      DO7L=IJA(K),IJA(K+1)-1
      ROW(IJA(L))=A(L)
7     CONTINUE
      IF(HALF)THEN
      HD=LINK(K)
      DO9L=1,N
      IF(HD.EQ.0)THEN
      GOTO10
      ENDIF
      ROW(IPTR(HD))=A(HD)
      HD=LINK(HD)
9     CONTINUE
10    CONTINUE
      ENDIF
      DO11L=IJA(K),IJA(K+1)-1
      IJAL=IJA(L)
      BCOL=IC(IJAL)-NBLACK
      IF(BCOL.GT.0)THEN
      D=A(L)*D2I(BCOL)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO13J=IJA(IJAL),IJA(IJAL+1)-1
      ROW(IJA(J))=ROW(IJA(J))-A(J)*D
13    CONTINUE
      IF(HALF)THEN
      HD=LINK(IJAL)
      DO15J=1,N
      IF(HD.EQ.0)THEN
      GOTO16
      ENDIF
      ROW(IPTR(HD))=ROW(IPTR(HD))-A(HD)*D
      HD=LINK(HD)
15    CONTINUE
16    CONTINUE
      ENDIF
      RSRHS(I)=RSRHS(I)-D*RHS(IJAL)
      ENDIF
11    CONTINUE
      IF(HALF)THEN
      HDO=LINK(K)
      DO17L=1,N
      IF(HDO.EQ.0)THEN
      GOTO18
      ENDIF
      IJAL=IPTR(HDO)
      BCOL=IC(IJAL)-NBLACK
      IF(BCOL.GT.0)THEN
      D=A(HDO)*D2I(BCOL)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO19J=IJA(IJAL),IJA(IJAL+1)-1
      ROW(IJA(J))=ROW(IJA(J))-A(J)*D
19    CONTINUE
      HD=LINK(IJAL)
      DO21J=1,N
      IF(HD.EQ.0)THEN
      GOTO22
      ENDIF
      ROW(IPTR(HD))=ROW(IPTR(HD))-A(HD)*D
      HD=LINK(HD)
21    CONTINUE
22    CONTINUE
      RSRHS(I)=RSRHS(I)-D*RHS(IJAL)
      ENDIF
      HDO=LINK(HDO)
17    CONTINUE
18    CONTINUE
      ENDIF
      DO23M=IJRS(I),IJRS(I+1)-1
      RS(M)=ROW(C(IJRS(M)))
23    CONTINUE
      RS(I)=ROW(K)
3     CONTINUE
      RETURN
      END
