      SUBROUTINEPCSC1P(NBLACK,N,C,IC,IJA,A,V1,V2)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERNBLACK,N,C(*),IC(*),IJA(*)
      DOUBLEPRECISIONA(*),V1(*),V2(*)
      INTEGERI,II,J,JJ
      DO1II=1,N
      I=IC(II)
      DO3JJ=IJA(II),IJA(II+1)-1
      J=IC(IJA(JJ))
      IF(I.GT.NBLACK.AND.J.LE.NBLACK)THEN
      V2(J)=V2(J)-A(JJ)*V1(I-NBLACK)
      ELSE
      IF(I.LE.NBLACK.AND.J.GT.NBLACK)THEN
      V2(I)=V2(I)-A(JJ)*V1(J-NBLACK)
      ENDIF
      ENDIF
3     CONTINUE
1     CONTINUE
      RETURN
      END
