      SUBROUTINEPCSD2F(N,IBLKN,IBLKS,IBTRM,IRTBM,IBTRMC,NBLCKB,
     *ND2I,C,IC,IJA,LINK,IPTR,A,ID2I,D2I,IRC)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IBLKN,IBLKS(*),IBTRM(*),IRTBM(*),IBTRMC(*),
     *NBLCKB,ND2I,C(*),IC(*),IJA(*),LINK(*),IPTR(*),
     *ID2I(*),IRC
      DOUBLEPRECISIONA(*),D2I(*)
      LOGICALLOWER,UPPER,FULL,HALF,SYMMAT
      COMMON/PCVERL/LOWER,UPPER,FULL,HALF,SYMMAT
      SAVE/PCVERL/
      INTEGERI,K,L,BCOL,IROW,ICOL,ROW,RAWBCL,
     *BD2I,ROWOFF,NN,HD
      CALLPC0V(ND2I,D2I)
      ID2I(1)=1
      BD2I=1
      DO1I=NBLCKB+1,IBLKN
      ROW=C(I)
      ROWOFF=BD2I-1
      NN=IBLKS(ROW)
      ID2I(I-NBLCKB)=BD2I
      DO3K=IBTRM(ROW),IBTRM(ROW+1)-1
      IROW=1-IBTRM(ROW)+K
      D2I(ROWOFF+IROW)=A(K)
      DO5L=IJA(K),IJA(K+1)-1
      RAWBCL=IRTBM(IJA(L))
      BCOL=IC(RAWBCL)
      ICOL=IJA(L)-IBTRM(RAWBCL)+1
      IF(BCOL.EQ.I)THEN
      D2I(ROWOFF+ICOL)=A(L)
      ENDIF
5     CONTINUE
      IF(HALF)THEN
      HD=LINK(K)
      DO7L=1,N
      IF(HD.EQ.0)THEN
      GOTO8
      ENDIF
      RAWBCL=IRTBM(IPTR(HD))
      BCOL=IC(RAWBCL)
      ICOL=IPTR(HD)-IBTRM(RAWBCL)+1
      IF(BCOL.EQ.I)THEN
      D2I(ROWOFF+ICOL)=A(HD)
      ENDIF
      HD=LINK(HD)
7     CONTINUE
8     CONTINUE
      ENDIF
      ROWOFF=ROWOFF+NN
3     CONTINUE
      CALLPCSPFA(NN,NN,D2I(BD2I),IRC)
      IF(IRC.NE.0)THEN
      IRC=IRC+IBTRM(ROW)-1
      RETURN
      ENDIF
      BD2I=BD2I+NN*NN
1     CONTINUE
      RETURN
      END
