      SUBROUTINEPCSD2S(IBLKN,IBLKS,NBLCKB,C,D2I,V)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERIBLKN,IBLKS(*),NBLCKB,C(*)
      DOUBLEPRECISIONV(*),D2I(*)
      INTEGERK,I,J,JJ,KK
      K=1
      J=1
      DO1I=NBLCKB+1,IBLKN
      JJ=IBLKS(C(I))
      KK=JJ*JJ
      CALLPCSPSL(JJ,JJ,D2I(K),V(J))
      K=K+KK
      J=J+JJ
1     CONTINUE
      RETURN
      END
