      SUBROUTINEPCSPSL(NN,M,LDLT,V)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERNN,M
      DOUBLEPRECISIONLDLT(*),V(*)
      INTEGERPROW,I,ONE
      DOUBLEPRECISIONDDOT
      ONE=1
      PROW=1
      DO1I=2,NN
      PROW=PROW+M
      V(I)=V(I)-DDOT(I-1,LDLT(PROW),ONE,V,ONE)
1     CONTINUE
      PROW=0
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO3I=1,NN
      V(I)=V(I)*LDLT(PROW+I)
      PROW=PROW+M
3     CONTINUE
      PROW=PROW+1
      DO5I=NN,2,-1
      PROW=PROW-M
      CALLDAXPY(I-1,-V(I),LDLT(PROW),1,V,1)
5     CONTINUE
      RETURN
      END
