      SUBROUTINEPCSRSP(N,NZRSMX,NBLACK,C,IC,IJA,IPTR,LINK,NZRS
     *,IRC,IJRS,MARK,FIC)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NZRSMX,NBLACK,C(*),IC(*),IJA(*),IPTR(*),LINK(*),
     *NZRS,IRC,IJRS(*),MARK(*),FIC(*)
      INTEGERI,J,K,L,JJ,LL,IFIC,BCOL,PCOL,IJAL
      CALLPC0VI(N,MARK)
      IJRS(1)=NBLACK+2
      NZRS=NBLACK+1
      DO1I=1,NBLACK
      MARK(I)=I
      IFIC=0
      K=C(I)
      DO3L=IJA(K),IJA(K+1)-1
      IJAL=IJA(L)
      BCOL=IC(IJAL)
      IF(BCOL.LE.NBLACK.AND.BCOL.GT.I)THEN
      IF(MARK(BCOL).NE.I)THEN
      MARK(BCOL)=I
      IFIC=IFIC+1
      FIC(IFIC)=BCOL
      ENDIF
      ELSE
      DO5J=IJA(IJAL),IJA(IJAL+1)-1
      PCOL=IC(IJA(J))
      IF(MARK(PCOL).NE.I.AND.PCOL.GT.I)THEN
      MARK(PCOL)=I
      IFIC=IFIC+1
      FIC(IFIC)=PCOL
      ENDIF
5     CONTINUE
      J=LINK(IJAL)
      DO7JJ=1,N
      IF(J.EQ.0)THEN
      GOTO8
      ENDIF
      PCOL=IC(IPTR(J))
      IF(MARK(PCOL).NE.I.AND.PCOL.GT.I)THEN
      MARK(PCOL)=I
      IFIC=IFIC+1
      FIC(IFIC)=PCOL
      ENDIF
      J=LINK(J)
7     CONTINUE
8     CONTINUE
      ENDIF
3     CONTINUE
      L=LINK(K)
      DO9LL=1,N
      IF(L.EQ.0)THEN
      GOTO10
      ENDIF
      IJAL=IPTR(L)
      BCOL=IC(IJAL)
      IF(BCOL.LE.NBLACK.AND.BCOL.GT.I)THEN
      IF(MARK(BCOL).NE.I)THEN
      MARK(BCOL)=I
      IFIC=IFIC+1
      FIC(IFIC)=BCOL
      ENDIF
      ELSE
      DO11J=IJA(IJAL),IJA(IJAL+1)-1
      PCOL=IC(IJA(J))
      IF(MARK(PCOL).NE.I.AND.PCOL.GT.I)THEN
      MARK(PCOL)=I
      IFIC=IFIC+1
      FIC(IFIC)=PCOL
      ENDIF
11    CONTINUE
      J=LINK(IJAL)
      DO13JJ=1,N
      IF(J.EQ.0)THEN
      GOTO14
      ENDIF
      PCOL=IC(IPTR(J))
      IF(MARK(PCOL).NE.I.AND.PCOL.GT.I)THEN
      MARK(PCOL)=I
      IFIC=IFIC+1
      FIC(IFIC)=PCOL
      ENDIF
      J=LINK(J)
13    CONTINUE
14    CONTINUE
      ENDIF
      L=LINK(L)
9     CONTINUE
10    CONTINUE
      IF(IFIC+NZRS.GT.NZRSMX)THEN
      IRC=IFIC*(N-I+1)/I
      RETURN
      ENDIF
      DO15J=1,IFIC
      NZRS=NZRS+1
      IJRS(NZRS)=FIC(J)
15    CONTINUE
      IJRS(I+1)=NZRS+1
1     CONTINUE
      IRC=0
      RETURN
      END
