      SUBROUTINEPCSRIJ(N,IJA,IJAP)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*),IJAP(*)
      INTEGERI
      CALLPCSRIZ(N,IJA,IJAP)
      CALLPCSRIX(N,IJA,IJAP)
      DO1I=1,N
      IJA(I)=IJA(I+1)
1     CONTINUE
      CALLPCSRIX(N,IJAP,IJA)
      RETURN
      END
