      SUBROUTINEPCSROP(N,IJA,IPTR,LINK,NBLACK,P,IP)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NBLACK,IJA(*),IPTR(*),LINK(*),P(*),IP(*)
      LOGICALLOWER,UPPER,FULL,HALF,SYMMAT
      COMMON/PCVERL/LOWER,UPPER,FULL,HALF,SYMMAT
      SAVE/PCVERL/
      INTEGERBACK,FRONT,I,IJ,J,K,MATCH,MTCHW,WHITE,KJ,COLOR,
     *IJJ,PBACK,IPJ,KK,RED,BLACK,NRED,NWHITE,NCORB,NCORW,
     *NCORR
      LOGICALFIRSTP
      NRED=0
      NWHITE=0
      NBLACK=0
      RED=0
      BLACK=0
      WHITE=N
      CALLPC0VI(N,IP)
      DO1K=1,N
      IF(IP(K).NE.0)THEN
      GOTO1
      ENDIF
      IP(K)=+1
      MATCH=0
      MTCHW=0
      FIRSTP=.TRUE.
      FRONT=1
      BACK=1
      P(FRONT)=K
      DO3KK=1,N
      IF(FRONT.GT.BACK)THEN
      GOTO4
      ENDIF
      I=P(FRONT)
      FRONT=FRONT+1
      IF(IP(I).EQ.2)THEN
      GOTO3
      ENDIF
      IF(FIRSTP)THEN
      COLOR=1
      FIRSTP=.FALSE.
      ELSE
      COLOR=0
      ENDIF
      PBACK=BACK
      DO5IJ=IJA(I),IJA(I+1)-1
      J=IJA(IJ)
      IPJ=IP(J)
      IF(ABS(IPJ).GT.1)THEN
      GOTO5
      ENDIF
      IF(IPJ.EQ.0)THEN
      IP(J)=-2
      BACK=BACK+1
      P(BACK)=J
      ELSEIF(COLOR.EQ.0)THEN
      COLOR=-IPJ
      ELSE
      IF(IPJ.EQ.COLOR)THEN
      IP(I)=2
      MTCHW=MTCHW+1
      DO7KJ=PBACK+1,BACK
      IP(P(KJ))=0
7     CONTINUE
      BACK=PBACK
      GOTO3
      ENDIF
      ENDIF
5     CONTINUE
      IF(HALF)THEN
      IJ=LINK(I)
      DO9IJJ=1,N
      IF(IJ.EQ.0)THEN
      GOTO10
      ENDIF
      J=IPTR(IJ)
      IPJ=IP(J)
      IF(ABS(IPJ).GT.1)THEN
      GOTO9
      ENDIF
      IF(IPJ.EQ.0)THEN
      IP(J)=-2
      BACK=BACK+1
      P(BACK)=J
      ELSEIF(COLOR.EQ.0)THEN
      COLOR=-IPJ
      ELSE
      IF(IPJ.EQ.COLOR)THEN
      IP(I)=2
      MTCHW=MTCHW+1
      DO11KJ=PBACK+1,BACK
      IP(P(KJ))=0
11    CONTINUE
      BACK=PBACK
      GOTO3
      ENDIF
      ENDIF
9     CONTINUE
10    CONTINUE
      ENDIF
      IP(I)=COLOR
      IF(COLOR.EQ.1)THEN
      MATCH=MATCH+1
      ENDIF
3     CONTINUE
4     CONTINUE
      IF(BACK-MTCHW-MATCH.GT.MATCH)THEN
      DO13I=1,BACK
      J=P(I)
      IF(IP(J).EQ.-1)THEN
      RED=RED+1
      IP(J)=RED
      ELSEIF(IP(J).EQ.1)THEN
      BLACK=BLACK-1
      IP(J)=BLACK
      ELSE
      WHITE=WHITE+1
      IP(J)=WHITE
      ENDIF
13    CONTINUE
      NRED=NRED+BACK-MTCHW-MATCH
      NBLACK=NBLACK+MATCH
      ELSE
      DO15I=1,BACK
      J=P(I)
      IF(IP(J).EQ.1)THEN
      RED=RED+1
      IP(J)=RED
      ELSEIF(IP(J).EQ.-1)THEN
      BLACK=BLACK-1
      IP(J)=BLACK
      ELSE
      WHITE=WHITE+1
      IP(J)=WHITE
      ENDIF
15    CONTINUE
      NRED=NRED+MATCH
      NBLACK=NBLACK+BACK-MTCHW-MATCH
      ENDIF
      NWHITE=NWHITE+MTCHW
1     CONTINUE
      NCORR=NBLACK+NWHITE
      NCORB=NBLACK+1
      NCORW=-NWHITE-NRED
      DO17I=1,N
      IF(IP(I).LT.0)THEN
      IP(I)=IP(I)+NCORB
      ELSEIF(IP(I).GT.N)THEN
      IP(I)=IP(I)+NCORW
      ELSE
      IP(I)=IP(I)+NCORR
      ENDIF
      P(IP(I))=I
17    CONTINUE
      NBLACK=NCORR
      RETURN
      END
