      SUBROUTINEPCSRRP(N,NRED,C,IC,IJA,A,RHS,D2I,V1,V2)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NRED,C(*),IC(*),IJA(*)
      DOUBLEPRECISIONA(*),RHS(*),D2I(*),V1(*),V2(*)
      INTEGERI,II,J,NBLACK,JJ
      NBLACK=N-NRED
      CALLPCPRMP(NRED,C(NBLACK+1),RHS,V2)
      DO1II=1,N
      I=IC(II)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO3JJ=IJA(II),IJA(II+1)-1
      J=IC(IJA(JJ))
      IF(I.GT.NBLACK.AND.J.LE.NBLACK)THEN
      V2(I-NBLACK)=V2(I-NBLACK)-A(JJ)*V1(J)
      ELSE
      IF(I.LE.NBLACK.AND.J.GT.NBLACK)THEN
      V2(J-NBLACK)=V2(J-NBLACK)-A(JJ)*V1(I)
      ENDIF
      ENDIF
3     CONTINUE
1     CONTINUE
      DO5I=1,NRED
      V2(I)=V2(I)*D2I(I)
5     CONTINUE
      RETURN
      END
