      SUBROUTINEPCSSCL(N,IJA,S,A)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*)
      DOUBLEPRECISIONS,A(*)
      INTEGERK
      DO1K=1,N
      A(IJA(K))=A(IJA(K))*S
1     CONTINUE
      RETURN
      END
