      SUBROUTINEPCTRAN(N,IJA,A,IJAL,AL)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*),IJAL(*)
      DOUBLEPRECISIONA(*),AL(*)
      INTEGERI,J
      CALLPCSRIZ(N,IJA,IJAL)
      DO1I=N,1,-1
      AL(I)=A(I)
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO3J=IJA(I),IJA(I+1)-1
      IJAL(IJA(J))=IJAL(IJA(J))-1
      IJAL(IJAL(IJA(J)))=I
      AL(IJAL(IJA(J)))=A(J)
3     CONTINUE
1     CONTINUE
      RETURN
      END
