      SUBROUTINEPCVERF(N,IJA,X)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,IJA(*)
      DOUBLEPRECISIONX(*)
      INTEGERIERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,LUDONE,IBLK,
     *MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,IFRMAT
      COMMON/PCCOM1/IERR,ITMAX,ITEST,KMAX,IFL,IPRE,PBLK,
     *LUDONE,IBLK,MNEED,ITS,RSDONE,NOVERF,RED1,RED2,IERR2,
     *IFRMAT
      SAVE/PCCOM1/
      INTEGERISRT,IJASGN,ISX0,IFORM
      COMMON/PCVERI/ISRT,IJASGN,ISX0,IFORM
      SAVE/PCVERI/
      LOGICALLOWER,UPPER,FULL,HALF,SYMMAT
      COMMON/PCVERL/LOWER,UPPER,FULL,HALF,SYMMAT
      SAVE/PCVERL/
      INTEGERI,J
      IF(IJA(N+1).EQ.N+2)THEN
      IERR=20
      RETURN
      ENDIF
      SYMMAT=.FALSE.
      LOWER=.FALSE.
      UPPER=.FALSE.
      FULL=.TRUE.
      HALF=.FALSE.
      IFORM=0
      IJASGN=1
      DO1I=1,N
      IF(IJA(I).LT.0)THEN
      IJASGN=0
      GOTO2
      ENDIF
1     CONTINUE
2     CONTINUE
      IF(IJASGN.EQ.0.AND.IBLK.NE.0)THEN
      IERR2=I
      IERR=17
      RETURN
      ENDIF
      IF(IJASGN.EQ.1.AND.IBLK.EQ.0)IBLK=1
      ISX0=1
      DO13I=1,N
      IF(X(I).NE.0.0D0)THEN
      ISX0=0
      GOTO14
      ENDIF
13    CONTINUE
14    CONTINUE
      IF(NOVERF.NE.0)THEN
      RETURN
      ENDIF
      IF(IJASGN.EQ.1)THEN
      DO3I=2,N+1
      IF(IJA(I).LT.IJA(I-1))THEN
      IERR2=I
      IERR=17
      RETURN
      ENDIF
3     CONTINUE
      ELSE
      DO5I=2,N+1
      IF(ABS(IJA(I)).LT.ABS(IJA(I-1)))THEN
      IERR2=I
      IERR=17
      RETURN
      ENDIF
5     CONTINUE
      IF(IJA(N+1).LT.0)THEN
      IERR=17
      IERR2=N+1
      RETURN
      ENDIF
      ENDIF
CDIR$ IVDEP
CVDIR IGNORE RECRDEPS
      DO7J=ABS(IJA(1)),ABS(IJA(N+1))-1
      IF(IJA(J).LT.1.OR.IJA(J).GT.N)THEN
      IERR2=J
      IERR=17
      RETURN
      ENDIF
7     CONTINUE
      ISRT=1
      DO9I=1,N
      DO11J=ABS(IJA(I))+1,ABS(IJA(I+1))-1
      IF(IJA(J).LE.IJA(J-1))THEN
      ISRT=0
      GOTO10
      ENDIF
11    CONTINUE
9     CONTINUE
10    CONTINUE
      RETURN
      END
