      SUBROUTINEPCVTM(N,V,NC,M,W)
      IMPLICITDOUBLEPRECISION(A-H,O-Z)
      INTEGERN,NC
      DOUBLEPRECISIONV(*),M(N,*),W(*),DDOT
      INTEGERI,ONE
      ONE=1
      DO1I=1,NC
      W(I)=DDOT(N,V,ONE,M(1,I),ONE)
1     CONTINUE
      RETURN
      END
