CC = cl
CFLAGS = /c /nologo /EHsc /D_CRT_SECURE_NO_DEPRECATE /O2 /DWIN32 

LIBTOOL = lib /nologo
DEL = del

LIB_TARGET = tinyxml.lib
			
.cpp.obj :
	$(CC) $(CFLAGS) $<

default all:	$(LIB_TARGET)

CPPOBJECTS = tinystr.obj tinyxml.obj tinyxmlerror.obj tinyxmlparser.obj
    
$(LIB_TARGET) : $(OBJDIR) $(CPPOBJECTS)
	$(LIBTOOL) /out:$@ $(CPPOBJECTS)
		
clean:
	$(DEL) $(LIB_TARGET) $(CPPOBJECTS)
	