CC = cl
CFLAGS = /c /EHsc /O2 /nologo /DWIN32 /DUSE_VC_MEMORY_MANAGER  -I..\Optimization2

LIBTOOL = lib /nologo
DEL = del

TARGET = cfsqp.lib

.c.obj:	
	$(CC) /c $(CFLAGS) /Fo$@ $<

default all: $(TARGET)

COBJECTS =	cfsqp.obj	\
			qld.obj	\
			globals.obj	
			
$(TARGET):	$(COBJECTS)
	$(LIBTOOL) $(COBJECTS) /out:$@

clean:
	$(DEL) $(TARGETS) $(COBJECTS)
