CC = gcc

CFLAGS = -c -O2 -fPIC -DMACOSX -DUSE_VC_MEMORY_MANAGER  -I../Optimization

TARGETS=	libcfsqp.a

.SUFFIXES:		.c.o


.c.o:	
	$(CC) $(CFLAGS)  $<

default all:		$(TARGETS)

COBJECTS =	 cfsqp.o	\
			qld.o		

$(TARGETS):	$(COBJECTS)
	ar cru $@ $(COBJECTS) 
	ranlib $@


clean:
	rm $(TARGETS) $(COBJECTS)

depend:
	makedepend -Y -f Makefile.linux -- $(CFLAGS) -- *.c *.cpp
