FROM ubuntu:xenial as build

RUN apt-get -y update && apt-get install -y apt-utils && \
    apt-get install -y -qq -o=Dpkg::Use-Pty=0 build-essential gfortran gdb cmake expect git

RUN apt-get install -y software-properties-common  python-software-properties

RUN add-apt-repository ppa:ubuntu-desktop/ubuntu-make
RUN	apt -y update
RUN apt-get install -y ubuntu-make

# note that \025 is Ctrl-U which should remove everything from cursor to start of line
# RUN export COMMAND="spawn umake ide eclipse-cpp;" \
#     SLEEP="sleep 3;" \
#     EXPECT_PROMPT="expect -re \"Choose installation path: /root/.local/share/umake/ide/eclipse-cpp\";" \
#     SEND="send \"\025/usr/local/opt/eclipse\r\n\";" \
#     TIMEOUT="set timeout -1;" \
#     EXPECT_DONE="expect -re \"Installation done\";" && \
#     expect -c "$COMMAND $SLEEP $EXPECT_PROMPT $SEND $TIMEOUT $EXPECT_DONE"

# note that \025 is Ctrl-U which should remove everything from cursor to start of line
RUN export COMMAND="spawn umake ide clion;" \
    SLEEP="sleep 3;" \
    EXPECT_PROMPT="expect -re \"Choose installation path: /root/.local/share/umake/ide/clion\";" \
    SEND="send \"\025/usr/local/opt/clion\r\n\";" \
    TIMEOUT="set timeout -1;" \
    EXPECT_DONE="expect -re \"Installation done\";" && \
    expect -c "$COMMAND $SLEEP $EXPECT_PROMPT $SEND $TIMEOUT $EXPECT_DONE"

# RUN apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc && \
#     apt-add-repository 'deb https://repos.codelite.org/ubuntu/ xenial universe' && \
#     apt-get install -y apt-transport-https && \
#     apt-get -y update && \
#     apt-get install -y codelite

RUN apt-get install -y -qq -o=Dpkg::Use-Pty=0 zlib1g-dev libhdf5-dev libcurl4-openssl-dev libboost-dev

# RUN useradd -ms /bin/bash  developer
# USER developer
# ENV HOME /home/developer

VOLUME /workspace

WORKDIR /workspace/vcell-solvers

CMD /bin/bash

