all:
	cd cvode; make -f Makefile.linux
	cd ida; make -f Makefile.linux
	cd nvec_ser; make -f Makefile.linux
	cd sundials; make -f Makefile.linux

clean:
	cd cvode; make -f Makefile.linux clean
	cd ida; make -f Makefile.linux clean
	cd nvec_ser; make -f Makefile.linux clean
	cd sundials; make -f Makefile.linux clean
