CFLAGS =	/c /GX /O2 /DWIN32 -I..\ExpressionParser 

LIBS = ..\ExpressionParser\ExpParser.lib

STDALONE_TARGET = ExpressionParserTest.exe

.SUFFIXES:	.cpp.obj

.cpp.obj:	
	cl /c $(CFLAGS) /Fo$@ $<

default all:	$(STDALONE_TARGET)

STDALONE_CPPOBJECTS = ExpressionParserTest.obj 
		
$(STDALONE_TARGET): $(STDALONE_CPPOBJECTS)
	cl -Fe$@ $(STDALONE_CPPOBJECTS) $(LIBS)
		
clean:
	del $(STDALONE_TARGET)
	del $(STDALONE_CPPOBJECTS)
