# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "../..", "/vagrant_numerics"
  config.vm.provider "virtualbox" do |vb|
  	vb.name = "vcell-numerics-linux64"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y update
    sudo yum -y groupinstall "Development Tools"
    sudo yum -y install cmake.x86_64
    sudo yum -y install sqlite-devel.x86_64
    sudo yum -y install openssl-devel.x86_64
    sudo yum -y install wget
    wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz
    tar xvf cmake-3.8.1.tar.gz
    cd cmake-3.8.1
    ./configure --prefix=/opt/cmake
    gmake
    sudo gmake install
    sudo yum -y --enablerepo=extras install epel-release
    sudo yum -y install hdf5-devel.x86_64
    sudo yum -y install boost-devel.x86_64
    sudo yum -y install activemq-cpp-devel.x86_64
    sudo yum -y install hdf5-static.x86_64
    sudo yum -y install libgfortran-static.x86_64
    sudo yum -y install glibc-static.x86_64
    sudo yum -y install libstdc++-static.x86_64
    sudo yum -y install zlib-static.x86_64
SHELL
end
