default all:
	cd f90 && nmake -f Makefile.win32
	cd fortran && nmake -f Makefile.win32
	cd libsrc && nmake -f Makefile.win32
	
clean:
	cd f90 && nmake -f Makefile.win32 clean
	cd fortran && nmake -f Makefile.win32 clean
	cd libsrc && nmake -f Makefile.win32 clean