#!/bin/sh
#
# Copyright (C) 2002-2007, David Beckett http://www.dajobe.org/
# Copyright (C) 2002-2004, University of Bristol, UK http://www.bristol.ac.uk/
# 
# This package is Free Software and part of Redland http://librdf.org/
# 
# It is licensed under the following three licenses as alternatives:
#   1. GNU Lesser General Public License (LGPL) V2.1 or any newer version
#   2. GNU General Public License (GPL) V2 or any newer version
#   3. Apache License, V2.0 or any newer version
# 
# You may not use this file except in compliance with at least one of
# the above three licenses.
# 
# See LICENSE.html or LICENSE.txt at the top of this package for the
# complete terms and further detail along with the license texts for
# the licenses in COPYING.LIB, COPYING and LICENSE-2.0.txt respectively.
# 
# 
# 
#

prefix=/usr/local
exec_prefix=${prefix}

if test "${prefix}/include" != /usr/include ; then
  includes="-I${prefix}/include"
else
  includes=
fi


usage()
{
	cat<<EOF
Usage: raptor-config [OPTION]

known values for OPTION are:

  --prefix[=DIR]        change raptor prefix [default $prefix]
  --libs                print library linking information
  --libtool-libs        print linking information for use with libtool
  --private-libs        print library private/static linking information
  --cflags		print pre-processor and compiler flags
  --options		print raptor library compiled options
  --help                display this help and exit
  --version             output version information
  --version-decimal     output version as a decimal integer
EOF
  exit $1
}


if test $# -eq 0; then
  usage 1 1>&2
fi


while test $# -gt 0; do
  case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
        prefix=$optarg
        ;;
    --prefix)
      echo_prefix=yes
      ;;
    --version)
      echo 1.4.19
      exit 0
      ;;
    --version-decimal)
      echo 10419
      exit 0
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --options)
      echo_options=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    --libtool-libs)
      echo_libtool_libs=yes
      ;;
    --private-libs)
      echo_private_libs=yes
      ;;
    --help|--usage)
      usage 0
      ;;
    *)
      usage 1 1>&2
      ;;
  esac

  shift
done
  

if test "$echo_prefix" = "yes"; then
  echo $prefix
fi
if test "$echo_cflags" = "yes"; then
  echo $includes
fi
if test "$echo_options" = "yes"; then
  if test none != none; then
    echo "www-library: none"
  fi
  if test expat != none; then
    echo "xml-parser: expat"
  fi
  for parser in  rdfxml ntriples turtle trig guess rss-tag-soup rdfa none; do
    if test $parser != none; then
      echo "parser: $parser"
    fi
  done
  for serializer in  rdfxml rdfxml-abbrev turtle ntriples rss-1.0 dot json atom none; do
    if test $serializer != none; then
      echo "serializer: $serializer"
    fi
  done
fi
if test "$echo_libs" = "yes"; then
  echo -L${exec_prefix}/lib -lraptor
fi
if test "$echo_libtool_libs" = "yes"; then
  echo ${exec_prefix}/lib/libraptor.la
fi
if test "$echo_private_libs" = "yes"; then
  echo 
fi
