# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../..", "/vagrant_numerics"
  config.vm.provider "virtualbox" do |vb|
  	vb.name = "vcell-solvers-ubuntu64"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0  build-essential
    sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0  gfortran
    sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0  zlib1g-dev
    sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0  libhdf5-dev    
    
    #wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz
    #sudo tar xzf cmake-3.8.1.tar.gz
    #cd cmake-3.8.1
    #sudo ./configure --prefix=/opt/cmake
    #sudo make --quiet 
    #sudo make --quiet install
    
    sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0  cmake3    
    
SHELL
end
