# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "../..", "/vagrant_numerics"
  config.ssh.forward_x11 = true
  config.vm.provider "virtualbox" do |vb|
  	vb.name = "vcell-solvers-ubuntu64"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -y update && apt-get install -y apt-utils && \
    apt-get install -y -qq -o=Dpkg::Use-Pty=0 build-essential gfortran zlib1g-dev \
    libhdf5-dev libcurl4-openssl-dev libboost-dev cmake    
SHELL
end
