#include <vcellxml.h>
std::ostream & tinyxml2::operator<<(std::ostream &os, tinyxml2::XMLError sym) {
	switch (sym) {

#define CASE(x) case x: os << #x; break;

		CASE(XML_SUCCESS);
		CASE(XML_NO_ATTRIBUTE);
		CASE(XML_WRONG_ATTRIBUTE_TYPE);
		CASE(XML_ERROR_FILE_NOT_FOUND);
		CASE(XML_ERROR_FILE_COULD_NOT_BE_OPENED);
		CASE(XML_ERROR_FILE_READ_ERROR);
		CASE(XML_ERROR_ELEMENT_MISMATCH);
		CASE(XML_ERROR_PARSING_ELEMENT);
		CASE(XML_ERROR_PARSING_ATTRIBUTE);
		CASE(XML_ERROR_IDENTIFYING_TAG);
		CASE(XML_ERROR_PARSING_TEXT);
		CASE(XML_ERROR_PARSING_CDATA);
		CASE(XML_ERROR_PARSING_COMMENT);
		CASE(XML_ERROR_PARSING_DECLARATION);
		CASE(XML_ERROR_PARSING_UNKNOWN);
		CASE(XML_ERROR_EMPTY_DOCUMENT);
		CASE(XML_ERROR_MISMATCHED_ELEMENT);

#undef CASE 

default:
		os << "Unknown error (" <<static_cast<int>(sym) << ')';
	}
	return os;
}
