CC= gcc

# Compilation options
COPTIONS = -c -O2 -fexceptions -I../linux -I. -DHAVE_CONFIG_H 

SRCLIB = libnetcdf.a

#
%.o : %.c
	$(CC) $(COPTIONS) $<

default all: $(SRCLIB)

OBJS = attr.o \
	dim.o \
	error.o \
	libvers.o \
	nc.o \
	ncx.o \
	posixio.o \
	putget.o \
	string.o \
	v1hpg.o \
	v2i.o \
	var.o 

$(SRCLIB) : $(OBJS)
	ar cru $@ $(OBJS)
 
#
clean:
	rm $(SRCLIB) $(OBJS)
