#
#Fortran compiler
FC= ifort

# Compilation options
FOPTIONS = -c 

F90LIB = libnetcdf_f90.a

%.o : %.f90
	$(FC) $(FOPTIONS) $<

default all: $(F90LIB)

OBJS = typeSizes.o netcdf.o

$(F90LIB) : $(OBJS)
	ar cru $@ $(OBJS)
 
#
clean:
	rm $(OBJS) $(F90LIB) typeSizes.mod netcdf.mod
