/* source/smoldyn_config.h.  Generated by configure.  */
/* source/smoldyn_config.h.in.  Generated from configure.ac by autoheader.  */

/* Number of threads */
#define DEFAULT_NUMBER_THREADS 4

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <GLUT/glut.h> header file. */
/* #undef HAVE_GLUT_GLUT_H */

/* Define to 1 if you have the <GL/glut.h> header file. */
/* #undef HAVE_GL_GLUT_H */

/* Define to 1 if you have the <GL/glu.h> header file. */
/* #undef HAVE_GL_GLU_H */

/* Define to 1 if you have the <GL/gl.h> header file. */
/* #undef HAVE_GL_GL_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `glut' library (-lglut). */
/* #undef HAVE_LIBGLUT */

/* Define to 1 if you have the `tiff' library (-ltiff). */
/* #undef HAVE_LIBTIFF */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <OpenGL/glu.h> header file. */
/* #undef HAVE_OPENGL_GLU_H */

/* Define to 1 if you have the <OpenGL/gl.h> header file. */
/* #undef HAVE_OPENGL_GL_H */

/* Define if you have POSIX threads libraries and header files. */
/* #undef HAVE_PTHREAD */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Use nonstandard varargs form for the GLU tesselator callback */
/* #undef HAVE_VARARGS_GLU_TESSCB */

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Whether to compile Smoldyn with libmoleculizer support */
/* #undef LIBMOLECULIZER */

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Whether to compile Smoldyn with OpenGL support */
/* #undef OPENGL */

/* Name of package */
#define PACKAGE "smoldyn"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "steven.s.andrews@gmail.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "smoldyn"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "smoldyn 2.15"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "smoldyn"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.15"

/* Define to necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Whether to compile Smoldyn with threading support */
#define THREADING 1

/* Whether to compile Smoldyn with libmoleculizer support */
#define USE_LIBMOLECULIZER 0

/* Whether to compile Smoldyn with OpenGL support */
#define USE_OPENGL 0

/* Whether to compile Smoldyn with threading support */
#define USE_THREADING 1

/* Version number of package */
#define VERSION "2.15"

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING 1
